apiVersion: v1
kind: ConfigMap
metadata:
  name: app-a
  labels:
    app: app-a
    version: "1.0"
data:
  index.html: |-
    <html>
      <h1>Hello Canary!</h1>
      <p>This is version 1.0</p>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    app: app-a
    version: "1.0"
spec:
  selector:
    matchLabels:
      app: app-a
      version: "1.0"
  replicas: 3
  template:
    metadata:
      labels:
        app: app-a
        version: "1.0"
    spec:
      containers:
      - name: app-a
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: config
      volumes:
        - name: config
          configMap:
            name: app-a

---

apiVersion: v1
kind: Service
metadata:
  name: app-a
  labels:
    app: app-a
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    app: app-a
    version: "1.0"
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-a
  labels:
    app: app-a
    version: "1.0"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: local.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-a
            port:
              name: http
